#version: '2'
services:
  web:
    image: buig/sf-php8.2-apache
    container_name: gestorLate
    volumes:
      - .:/code
      - ./provisioning/sites-enabled:/etc/apache2/sites-enabled
    env_file:
      - .env.webapp
    ports:
      - 8085:80
    networks:
      - edu-shared
    tty: true

networks:
  edu-shared:
    external: true
